#!/bin/bash

ln -sf ~/.dotfiles/.local/share/scripts/ ~/.local/share

ln -sf ~/.dotfiles/.dmrc ~/.dotfiles
ln -sf ~/.dotfiles/.zshrc ~/.dotfiles

ln -sf ~/.dotfiles/.config/alacritty/ ~/.config
ln -sf ~/.dotfiles/.config/dconf/ ~/.config
ln -sf ~/.dotfiles/.config/dunst/ ~/.config
ln -sf ~/.dotfiles/.config/flameshot/ ~/.config
ln -sf ~/.dotfiles/.config/habito/ ~/.config
ln -sf ~/.dotfiles/.config/htop/ ~/.config
ln -sf ~/.dotfiles/.config/lf/ ~/.config
ln -sf ~/.dotfiles/.config/mpv/ ~/.config
ln -sf ~/.dotfiles/.config/neofetch/ ~/.config
ln -sf ~/.dotfiles/.config/nitrogen/ ~/.config
ln -sf ~/.dotfiles/.config/nvim/ ~/.config
ln -sf ~/.dotfiles/.config/qtile/ ~/.config
ln -sf ~/.dotfiles/.config/rofi/ ~/.config
ln -sf ~/.dotfiles/.config/Thunar/ ~/.config
ln -sf ~/.dotfiles/.config/zathura/ ~/.config
ln -sf ~/.dotfiles/.config/fish/ ~/.config

ln -sf ~/.dotfiles/.config/akregatorrc ~/.config
ln -sf ~/.dotfiles/.config/hyfetch.json ~/.config
ln -sf ~/.dotfiles/.config/mimeapps.list ~/.config
ln -sf ~/.dotfiles/.config/picom.conf ~/.config


