#!/bin/bash
cd ~/Sync/academics/linguistics/swag/
devour zathura $(fzf --height=50% \
    --margin=5%,2%,2%,5% \
    --layout=reverse-list \
    --border=double \
    --info=inline \
    --prompt="search::" \
    --pointer="->" \
    --marker="!!" \
    --preview='stat {}' \
    --preview-label='[ dir stats ]' \
    --header='CTRL-C or ESC to quit')
