#!/bin/bash

INRES="1920x1200"
OUTRES="1920x1200"
FPS="24"

ffmpeg -f x11grab -s "$INRES" -r "$FPS" -i :0.0 -f alsa -i hw:2 \
-i default -vcodec libx264 -s "$OUTRES" \
-acodec libmp3lame -ab 160k -ar 44100 \
-threads 2 -f mp4 $1
