#!/usr/bin/bash

selected_name="pomodoro"
selected=$selected_name

tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected pomo
fi

tmux switch-client -t $selected_name
