#!/usr/bin/bash

session="neorg"

tmux new-sesssion -d -s $session

window=0
tmux rename-window -t $session:$window "life"
tmux send-keys -t $session:$window 'vim -c "Neorg workspace life"' C-m

window=1
tmux rename-window -t $session:$window "notes"
tmux send-keys -t $session:$window 'vim -c "Neorg workspace notes"' C-m

window=2
tmux rename-window -t $session:$window "yt"
tmux send-keys -t $session:$window 'vim -c "Neorg workspace yt"' C-m

tmux attach-session -t $session
