# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'wfxr/tmux-power'
set -g @tmux_power_prefix_highlight_pos 'LR'
set-option -sa terminal-features ',alacritty:RGB'

# set -g stuff
set -g mouse on 
set -g default-terminal "screen-256color"
set -s escape-time 1
set -g status-right '#{prefix_highlight} | %a %Y-%m-%d %H:%M'

# binds
## changing prefix
unbind C-b
set-option -g prefix C-f
bind-key C-f send-prefix
unbind C-d

## window managing
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %
bind -r ^ last-window

## vim direction keys
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R
bind -r C-k resize-pane -U 5
bind -r C-j resize-pane -D 5
bind -r C-h resize-pane -L 5
bind -r C-l resize-pane -R 5

## sourcing tmux config + plugins
bind r source-file ~/.config/tmux/tmux.conf
run ~/.config/tmux/plugins/tpm/tpm

