# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'dracula/tmux'
set -g @plugin 'tmux-plugins/tmux-sidebar'
set -g @tmux_power_prefix_highlight_pos 'LR'
set-option -sa terminal-features ',alacritty:RGB'

set -g @dracula-plugins "network weather battery"
set -g @dracula-show-location false
set -g @dracula-show-fahrenheit false
set -g @dracula-synchronize-panes-label "Sync"
set-environment -g 'IGNOREEOF' 2

# set -g stuff
set -g mouse on 
set -g default-terminal "screen-256color"
set -s escape-time 1
set -g status-right '#{prefix_highlight} | %a %Y-%m-%d %H:%M'

set -g default-terminal "xterm-kitty"                                                                    
set -g terminal-overrides "xterm-kitty"                                                                                             
# true colours support                                                                                                              
# set -ga terminal-overrides ",*256col*:Tc"                                                                              
set -ga terminal-overrides ",xterm-256color:Tc"                                                                         
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'                                                   
# underscore colours - needs tmux-3.0                                                                                               
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

# binds
## changing prefix
unbind C-b
set-option -g prefix C-f
bind-key C-f send-prefix
unbind C-d

## window managing
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %
bind -r ^ last-window

## vim direction keys
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R
bind -r C-k resize-pane -U 5
bind -r C-j resize-pane -D 5
bind -r C-h resize-pane -L 5
bind -r C-l resize-pane -R 5

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

## sourcing tmux config + plugins
bind r source-file ~/.config/tmux/tmux.conf
run ~/.config/tmux/plugins/tpm/tpm

