# inactive-opacity = 0.90;
# active-opacity = 1.00;
# frame-opacity = 0.95;

shadow = true;
shadow-radius = 12;
shadow-opacity = .75;
shadow-offset-x = -10;
shadow-offset-y = -10;
shadow-color = "#000000"
shadow-exclude = [
  "name = 'Notification'",
  "class_g ?= 'i3bar'",
  "class_g = 'Conky'",
  "class_g = 'Dunst'",
  "class_g = 'conky_battery'",
  "class_g ?= 'Notify-osd'",
  "class_g = 'Cairo-clock'",
  "class_g = 'firefox' && window_type = 'utility'",
  "class_g = 'Polybar'",
  "_GTK_FRAME_EXTENTS@:c"
];

opacity-rule = [
  "100:_NET_WM_STATE@[0]:32a = '_NET_WM_STATE_FULLSCREEN'",
  "100:_NET_WM_STATE@[1]:32a = '_NET_WM_STATE_FULLSCREEN'",
  "100:_NET_WM_STATE@[2]:32a = '_NET_WM_STATE_FULLSCREEN'",
  "100:_NET_WM_STATE@[3]:32a = '_NET_WM_STATE_FULLSCREEN'",
  "100:_NET_WM_STATE@[4]:32a = '_NET_WM_STATE_FULLSCREEN'"
];

# if you want blur. performs really badly on low powered hardware (unusable)
# commenting out for consistency across computers
#blur-method = "kernel";
#blur-kern = "15,15,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,";

blur-kern       = "3x3box";
blur-background-exclude = [
	"window_type = 'dock'",
	"window_type = 'desktop'",
    "class_g = 'Polybar'",
    "class_g = 'firefox' && window_type = 'utility'",
	"_GTK_FRAME_EXTENTS@:c"
];

fading = true;
fading-delta = 14;
fade-in-step = 0.1;
face-out-step = 0.1;
