import = [
  # "~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"
  "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

live_config_reload = true

[window]
padding = { x = 25, y = 25 }

[env]
WINIT_X11_SCALE_FACTOR = "1.0"
TERM = "xterm-256color"

[font]
size = 11.5

[font.normal]
family = "terminal-font"
style = "Regular"

[shell]
program = "/usr/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux"]

[[hints.enabled]]
regex = "[^ ]+\\.rs:\\d+:\\d+"
command = { program = "code", args = [ "--goto" ] }
mouse = { enabled = true }
